#!/usr/bin/env bash
# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/helper.sh" ]]; then
  source "${_path}/helper.sh"
else
  echo "No helper-script found"
fi
# script will not hit this if there is no config-file to load
source "$(get_config)"
main() {
    # Running ps to get running processes and display in dmenu.
    selected="$(ps --user "$USER" -F | \
                ${DMENU} "Search for process to kill:" "$@" | \
                awk '{print $2" "$11}')";
    if [[ -n $selected ]]; then
        answer="$(echo -e "No\nYes" | ${DMENU} "Kill $selected?" "$@")"
        if [[ $answer == "Yes" ]]; then
            kill -9 "${selected%% *}"
            echo "Process $selected has been killed." && exit 0
        else
            echo "Program terminated." && exit 1
        fi
    fi
}
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"