#!/usr/bin/env bash
# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/helper.sh" ]]; then
  source "${_path}/helper.sh"
else
  echo "No helper-script found"
fi
# script will not hit this if there is no config-file to load
source "$(get_config)"
function main() {
  local _options=( "Search manpages" "Random manpage" "Quit")
  # We use "printf '%s\n'" to format the array one item to a line.
  choice=$(printf '%s\n' "${_options[@]}" | ${DMENU} ' ' "$@")
  # What to do when/if we choose one of the options.
  case "$choice" in
    'Search manpages')
          # shellcheck disable=SC2086
          man -k . | awk '{$3="-"; print $0}' | \
          ${DMENU} 'Search for:' | \
          awk '{print $2, $1}' | tr -d '()' | xargs $DMTERM man
    ;;
    'Random manpage')
          man -k . | cut -d' ' -f1 | shuf -n 1 | \
          ${DMENU} 'Random manpage:' | xargs $DMTERM man
    ;;
    'Quit')
      echo "Program terminated." && exit 0
    ;;
    *)
      exit 0
    ;;
  esac
}
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
